# sley configuration file
# Documentation: https://github.com/indaco/sley

# Enabled plugins:
#   - commit-parser
#   - tag-manager
#   - dependency-check

path: .version
plugins:
  # Analyzes conventional commits to suggest version bumps
  commit-parser: false
  # Automatically creates git tags after version changes
  tag-manager:
    enabled: true
  # Syncs version to package.json and other dependency files
  dependency-check:
    enabled: true
    auto-sync: true
    files:
      - path: package.json
        field: version
        format: json
extensions:
  - name: github-version-sync
    path: .sley-extensions/github-version-sync
    enabled: true
    config:
      repo: indaco/sley
